#!/bin/bash -l
# FILENAME:  simple_job_submission_file

#SBATCH -A myqueuename
#SBATCH --nodes=1 
#SBATCH --time=0:10:00
#SBATCH --job-name simple_test
#SBATCH --ntasks=10

module purge

# Print the hostname of the compute node on which this job is running.
/bin/hostname

srun --mpi=pmi2 apptainer run mpi.sif hello-world.py